spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: auth-service
  jpa:
    hibernate:
      naming:
        physical-strategy: com.codares.authservice.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy